export const GET_TODOS = "GET_TODOS";
export const DELTE_USER ="DELTE_USER"
export const ADD_USER ="ADD_USER"
export const SINGLE_TODO_DATA = "SINGLE_TODO_DATA"
export const UPDATE_DATA = "UPDATE_DATA"
export const REMOVE_SELECTED_TODO = "REMOVE_SELECTED_TODO"